import "../globals.css";
import { cn } from "@utils/cn";
import { Inter } from "next/font/google";
import { getSellerProfile, getUserProfile } from "@utils/get-profile";
import { Toaster } from "react-hot-toast";
import { SellerNavbar } from "@components/Navbar";
import ZustandWrapper from "@components/ZustandWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUserProfile();
  const seller = await getSellerProfile();

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen flex",
          seller ? "flex-row items-start" : "flex-col"
        )}
      >
        <ZustandWrapper myCart={null} {...{ user, seller }}>
          <SellerNavbar isSeller={!!seller} />

          <main
            className={cn(
              inter.className,
              "!p-4 flex flex-col h-full flex-1",
              !seller && "flex-col gap-8"
            )}
          >
            {children}
          </main>
        </ZustandWrapper>

        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
