import "../globals.css";
import { cn } from "@utils/cn";
import { Inter } from "next/font/google";
import { UserNavbar } from "@components/Navbar";
import { getSellerProfile, getUserProfile } from "@utils/get-profile";
import { Toaster } from "react-hot-toast";
import ZustandWrapper from "@components/ZustandWrapper";
import { DocumentData, DocumentReference, getDoc } from "firebase/firestore";
import { Cart, MyCart } from "types/cart";
import { filterDoc } from "@backend/lib";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUserProfile();
  const seller = await getSellerProfile();

  let cartItemsLength = 0;
  let userCart: MyCart<string>[] = [];

  if (user) {
    const { myCart } = (await filterDoc("cart", user?.cartId!)) as {
      id: string;
    } & Cart<DocumentReference<DocumentData>>;

    userCart = myCart.map((e) => ({ id: e.id.id, qty: e.qty }));

    cartItemsLength = myCart.length;
  }

  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ZustandWrapper {...{ user, seller, myCart: userCart }}>
          <UserNavbar
            {...{ isSeller: !!seller, isUser: !!user, cartItemsLength }}
          />

          <main
            className={cn(
              inter.className,
              "container !p-4 flex flex-col h-full flex-1"
            )}
          >
            {children}
          </main>
        </ZustandWrapper>

        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
